export const bookCategories: string[] = [
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Fantasy",
  "Thriller",
  "Mystery",
  "Horror",
  "Romance",
  "Historical Fiction",
  "Biography & Autobiography",
  "Self-Help",
  "Philosophy",
  "Science & Technology",
  "History",
  "Poetry",
  "Young Adult (YA)",
  "Children's Literature",
  "Graphic Novel & Comic",
  "Travel",
  "Cookbooks",
  "Art & Photography",
  "Dystopian",
  "Business / Economics",
];
